# Usually, this file would live inside .cargo/config.toml, but then R CMD check
# would complain about hidden files, as in
#
# ❯ checking for hidden files and directories ... NOTE
#   Found the following hidden files and directories:
#     src/rust/.cargo
#   These were most likely included in error. See section ‘Package
#   structure’ in the ‘Writing R Extensions’ manual.
#
# To circumvent this, we place the file directly next to Cargo.toml and
# move it to .cargo/config.toml at install-time.

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/SombkeMaximilian/metabodecon-rust?rev=d73d0883894e0eb006c8b0951c709f6343672b1c"]
git = "https://github.com/SombkeMaximilian/metabodecon-rust"
rev = "d73d0883894e0eb006c8b0951c709f6343672b1c"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
