name: Test-Install
permissions: read-all

on: {
  push: {branches: [main, master]},
  pull_request: {branches: [main, master]}
}

jobs:

  test-github-install:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          # Ubuntu (should work for all versions)
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel'}
          - {os: ubuntu-latest,  r: '4.2'}
          # MacOS (should work for all versions)
          - {os: macos-latest,   r: 'release'}
          - {os: macos-latest,   r: '4.2'}
          # Windows (should work for 4.2 and greater)
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '4.2'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RUN_SLOW_TESTS: "TRUE"
    steps:

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install MacOS System Dependencies
        uses: r-hub/actions/setup-r-sysreqs@v1
        with: {type: "minimal"}

      - name: Install Linux System Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libgsl0-dev libcurl4-openssl-dev

      - name: Test Installation from Github
        shell: Rscript {0}
        run: |
          install.packages("pak")
          pak::pkg_install("spang-lab/mdrb")
